const fs = require("fs");
const path = require("path");

const outDir = path.join(__dirname, "../out");
const htaccessSource = path.join(__dirname, "../.htaccess");
const htaccessDestination = path.join(
  outDir,
  ".htaccess"
);

// Ensure out directory exists
if (!fs.existsSync(outDir)) {
  fs.mkdirSync(outDir, {
    recursive: true,
  });
}

// Copy .htaccess to out directory
if (fs.existsSync(htaccessSource)) {
  fs.copyFileSync(
    htaccessSource,
    htaccessDestination
  );

  console.log(
    "✅ .htaccess file copied to out directory"
  );
} else {
  console.warn(
    "⚠️ .htaccess source file not found"
  );
}

// Validate XML sitemap files
function validateSitemapFile(filePath) {
  if (!fs.existsSync(filePath)) {
    return false;
  }

  const content = fs.readFileSync(
    filePath,
    "utf8"
  );

  if (
    !content.includes(
      '<?xml version="1.0" encoding="UTF-8"?>'
    )
  ) {
    console.error(
      `❌ Invalid sitemap format in ${filePath}`
    );

    return false;
  }

  return true;
}

// Check and validate sitemap files
const sitemapFiles = [
  "sitemap.xml",
  "sitemap-services.xml",
  "sitemap-images.xml",
  "sitemap-index.xml",
];

sitemapFiles.forEach((file) => {
  const filePath = path.join(
    outDir,
    file
  );

  if (validateSitemapFile(filePath)) {
    console.log(
      `✅ ${file} validated successfully`
    );
  } else {
    console.warn(
      `⚠️ ${file} not found or invalid`
    );
  }
});

// robots.txt is generated by app/robots.ts.
// Verify rather than rewrite, so there is one owner.
const robotsPath = path.join(
  outDir,
  "robots.txt"
);

if (!fs.existsSync(robotsPath)) {
  console.warn(
    "⚠️ robots.txt missing from out/ — check app/robots.ts"
  );
} else {
  const robotsContent = fs.readFileSync(
    robotsPath,
    "utf8"
  );

  const missing = sitemapFiles.filter(
    (file) =>
      !robotsContent.includes(`/${file}`)
  );

  if (missing.length > 0) {
    console.warn(
      `⚠️ robots.txt does not reference: ${missing.join(
        ", "
      )}`
    );
  } else {
    console.log(
      "✅ robots.txt references all sitemaps"
    );
  }
}